# Generated by Django 5.0.3 on 2024-03-31 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_subjects_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'academic_subjects',
            },
        ),
        migrations.CreateModel(
            name='Listeners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listeners_surname', models.CharField(max_length=30)),
                ('listeners_name', models.CharField(max_length=30)),
                ('listeners_patronymic', models.CharField(max_length=30)),
                ('listeners_date_of_birth', models.DateField()),
                ('listeners_telephone', models.CharField(max_length=11)),
                ('listeners_e_mail', models.CharField(max_length=50)),
                ('listeners_password', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'listeners',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers_surname', models.CharField(max_length=30)),
                ('teachers_name', models.CharField(max_length=30)),
                ('teachers_patronymic', models.CharField(max_length=30)),
                ('teachers_telephone', models.CharField(max_length=11)),
                ('teachers_e_mail', models.CharField(max_length=50)),
                ('teachers_qualification', models.CharField(max_length=100)),
                ('teachers_work_experience', models.CharField(max_length=100)),
                ('teachers_academic_subjects_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_academic_subjects_id_fk', to='project_core.academic_subjects')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Journal_of_academic_performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_of_academic_performance_lesson_price', models.IntegerField()),
                ('journal_of_academic_performance_score_for_test_1', models.IntegerField()),
                ('journal_of_academic_performance_score_for_test_2', models.IntegerField()),
                ('journal_of_academic_performance_score_for_test_3', models.IntegerField()),
                ('journal_of_academic_performance_score_for_exam', models.IntegerField()),
                ('journal_of_academic_performance_listeners_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_of_academic_performance_listeners_id_fk', to='project_core.listeners')),
                ('journal_of_academic_performance_teachers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_of_academic_performance_teachers_id_fk', to='project_core.teachers')),
            ],
            options={
                'db_table': 'journal_of_academic_performance',
            },
        ),
    ]
